version: '3'

services:
  web:
    image: nginx:stable-alpine
    container_name: nginx_app
    restart: "unless-stopped"
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  mysql:
    platform: linux/amd64
    image: mysql:latest
    container_name: mysql_app
    restart: "unless-stopped"
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php_app
    restart: "unless-stopped"
    volumes:
    - .:/var/www/html
    ports:
    - "9003:9000"